GET http://localhost:3827/users/1881784875478630400/svm-balance
Content-Type: application/json

{ 
    "prompt": "@TestBots28 tip 0.01 sol to B3oQQv6K3VX9wjMkWd426ykHKYamqQvTXuwwLFMSVav3"
}

# GET http://localhost:3000
# Content-Type: application/json

# # {
# #     "prompt": "Swap 1 usdc on solana to usdc on base"
# # }


