POST http://localhost:3000/xfi-agent
Content-Type: application/json

{
    "prompt": " ekete.base.eth"
}

# GET http://localhost:3000
# Content-Type: application/json

# # {
# #     "prompt": "Swap 1 usdc on solana to usdc on base"
# # }